#!/bin/sh -e
NETWORK=${NETWORK:-"kazoo"}
#docker exec -i kazoo.$NETWORK /opt/kazoo/core/sup/priv/sup -n kazoo -c change_me $*
#docker exec -i kazoo.$NETWORK /opt/kazoo/core/sup/priv/sup -n kazoo $*
docker exec -i kazoo.$NETWORK sup $*